# -*- coding: utf-8 -*-
"""atv_IA_flowers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0vlX9iGPRxfaonAm2RygQ3AN8PEvMNh

# 1) Implemente uma **rede neural convolucional CNN** para classificação dabase de dados que se encontra para download neste [link](https://www.kaggle.com/datasets/rahmasleam/flowers-dataset):

Puxando e validando o arquivo do meu drive:
"""

from google.colab import drive

drive.mount('/content/drive')

!ls "/content/drive/MyDrive"

!unzip "/content/drive/MyDrive/flowers-dataset.zip"

import os

for root, dirs, files in os.walk("."):
    print(root)

    if len(dirs) > 0:
        print(dirs)

    if "daisy" in dirs:
        break

!pip install seaborn -q

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

DATASET_PATH = "flower_photos"

"""ITEM A) Implemente no algoritmo a divisão de dados 70% para treino, 15%
para validação e 15% para teste
"""

# ITEM A)
# conjunto de treino (70%)
train_ds = tf.keras.utils.image_dataset_from_directory(
    DATASET_PATH,
    validation_split=0.30,
    subset="training",
    seed=42,
    image_size=(224,224),
    batch_size=32
)

# conjunto temporário (30%)
temp_ds = tf.keras.utils.image_dataset_from_directory(
    DATASET_PATH,
    validation_split=0.30,
    subset="validation",
    seed=42,
    image_size=(224,224),
    batch_size=32
)

# 15% pra teste e 15% para validação

val_size = len(temp_ds) // 2

val_ds = temp_ds.take(val_size)

test_ds = temp_ds.skip(val_size)

# mostra as classes
class_names = train_ds.class_names

print(class_names)

# desempenho
AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.prefetch(AUTOTUNE)
val_ds = val_ds.prefetch(AUTOTUNE)
test_ds = test_ds.prefetch(AUTOTUNE)

"""B) Implemente um dos modelos de rede neural convolucional CNN
(escolha um modelo), podendo ser uma ResNet50, InceptionNet,
XCeptionNet, EfficientNet, VGGNet, DenseNet, ShuffleNetV2,
SquezzeNet, InceptionResNetV2, SENetResNet ou MobileNet.
"""

# MOBILENETV2
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224,224,3),
    include_top=False,
    weights='imagenet'
)

base_model.trainable = False

model = tf.keras.Sequential([
    tf.keras.layers.Rescaling(1./255),

    base_model,

    tf.keras.layers.GlobalAveragePooling2D(),

    tf.keras.layers.Dense(
        128,
        activation='relu'
    ),

    tf.keras.layers.Dropout(0.3),

    tf.keras.layers.Dense(
        5,
        activation='softmax'
    )
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

#Épocas
import time #calcula tbm o tempo
inicio = time.time()
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=10
)
fim = time.time()

"""ITEM C) (0,1) Implemente as métricas de classificação acurácia, precisão,
revocação (do inglês, reccal) e pontuação-F1 (do inglês, F1-score). O
algoritmo deve exibir na tela essas quatro métricas para serem colocadas
no arquivo .pdf como resultado.
"""

y_true = []
y_pred = []

for images, labels in test_ds:

    pred = model.predict(
        images,
        verbose=0
    )

    y_true.extend(labels.numpy())

    y_pred.extend(
        np.argmax(pred, axis=1)
    )

#acurácia
acc = accuracy_score(
    y_true,
    y_pred
)

print("Accuracy =", acc)

#Precisão
prec = precision_score(
    y_true,
    y_pred,
    average='weighted'
)

print("Precision =", prec)

#Recall
rec = recall_score(
    y_true,
    y_pred,
    average='weighted'
)

print("Recall =", rec)

#f1 score
f1 = f1_score(
    y_true,
    y_pred,
    average='weighted'
)

print("F1 Score =", f1)

"""Item d) (0,1) Implemente a exibição das curvas acurácia e validação da acurácia
mais perda (do inglês, loss) e validação da perda (do inglês, validation
loss) em dois eixos cartesianos. O algoritmo deve exibir na tela estas
representações gráficas, sendo duas curvas em cada um dos planos
cartesianos e, deve ser colocado no arquivo .pdf como parte do resultado.
"""

# Curva de Acurácia
plt.figure(figsize=(8,5))

plt.plot(
    history.history['accuracy'],
    label='Treino'
)

plt.plot(
    history.history['val_accuracy'],
    label='Validação'
)

plt.title('Accuracy')

plt.xlabel('Época')

plt.ylabel('Accuracy')

plt.legend()

plt.show()

# Curva de Loss
plt.figure(figsize=(8,5))

plt.plot(
    history.history['loss'],
    label='Treino'
)

plt.plot(
    history.history['val_loss'],
    label='Validação'
)

plt.title('Loss')

plt.xlabel('Época')

plt.ylabel('Loss')

plt.legend()

plt.show()

"""Item e) Implemente a exibição da matriz de confusão com os valores
numéricos das predições e valores numéricos percentuais, referente aos
valores numéricos de todas as cinco classes de flores. O algoritmo deve

exibir na tela a matriz de confusão, que deve ser colocada no arquivo .pdf
também como parte do resultado.
"""

from sklearn.metrics import confusion_matrix

# matriz de confusão
cm = confusion_matrix(
    y_true,
    y_pred
)

plt.figure(figsize=(8,6))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Classe Prevista")
plt.ylabel("Classe Verdadeira")

plt.title("Matriz de Confusão")

plt.show()

# calculo percentual da matriz de confusão
cm_percent = (
    cm.astype('float')
    /
    cm.sum(axis=1)[:, np.newaxis]
) * 100

# Exibição dela
plt.figure(figsize=(8,6))

sns.heatmap(
    cm_percent,
    annot=True,
    fmt=".1f",
    cmap='Greens',
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Classe Prevista")
plt.ylabel("Classe Verdadeira")

plt.title("Matriz de Confusão (%)")

plt.show()

"""Item f) (0,1) Implemente a exibição da curva ROC/AUC par a par entre as
classes, da seguinte forma: margarida com dente de leão, dente de leão
com rosas, rosas com girassol, girassol com tulipas e tulipas com
margarida. Os valore da AUC (área sobre a curva ROC do inglês, Area
Under the Curve) deve ser exibido no próprio eixo cartesiano onde está
plotado as curvas ROC, bem como também, todas as cinco curvas ROC
serem plotadas no mesmo eixo cartesiano. Da mesma forma que nos
itens anteriores, o algoritmo deve exibir na tela as curvas ROC/AUC que
deve ser colocada no arquivo .pdf como parte do resultado.
"""

print(class_names)

pairs = [
    (0,1),  # daisy x dandelion
    (1,2),  # dandelion x roses
    (2,3),  # roses x sunflowers
    (3,4),  # sunflowers x tulips
    (4,0)   # tulips x daisy
]

y_true = []
y_pred = []
y_prob = []

for images, labels in test_ds:

    probs = model.predict(
        images,
        verbose=0
    )

    preds = np.argmax(
        probs,
        axis=1
    )

    y_true.extend(labels.numpy())
    y_pred.extend(preds)
    y_prob.extend(probs)

y_true = np.array(y_true)
y_pred = np.array(y_pred)
y_prob = np.array(y_prob)

print(
    np.mean(
        np.argmax(y_prob, axis=1)
        ==
        y_pred
    )
)

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc

y_true_bin = label_binarize(
    y_true,
    classes=[0,1,2,3,4]
)

plt.figure(figsize=(10,8))

for i in range(len(class_names)):

    fpr, tpr, _ = roc_curve(
        y_true_bin[:, i],
        y_prob[:, i]
    )

    roc_auc = auc(
        fpr,
        tpr
    )

    plt.plot(
        fpr,
        tpr,
        linewidth=2,
        label=f"{class_names[i]} (AUC={roc_auc:.3f})"
    )

plt.plot(
    [0,1],
    [0,1],
    'k--',
    label='Aleatório'
)

plt.title(
    "Curvas ROC/AUC para Classificação das Flores",
    fontsize=14
)

plt.xlabel(
    "Taxa de Falsos Positivos (FPR)",
    fontsize=12
)

plt.ylabel(
    "Taxa de Verdadeiros Positivos (TPR)",
    fontsize=12
)

plt.legend(loc="lower right")

plt.grid(alpha=0.3)

plt.tight_layout()

plt.show()

"""g) (0,1) Implemente um gráfico de colunas verticais exibindo o valor numérico da quantidade de acertos e erros com os respectivos valores numéricos percentuais por classe, tendo como referência de acertos e erros por classe os rótulos verdadeiros das imagens do conjunto de teste. Da mesma forma, o algoritmo deve exibir na tela o gráfico de colunas verticais que deve ser colocada no arquivo .pdf como parte do resultado."""

import numpy as np
import pandas as pd

acertos = []
erros = []

perc_acertos = []
perc_erros = []

for classe in range(len(class_names)):

    # imagens da classe verdadeira
    mask = (y_true == classe)

    total = np.sum(mask)

    corretos = np.sum(
        (y_true == classe) &
        (y_pred == classe)
    )

    incorretos = total - corretos

    acertos.append(corretos)
    erros.append(incorretos)

    perc_acertos.append(
        100 * corretos / total
    )

    perc_erros.append(
        100 * incorretos / total
    )

resultado = pd.DataFrame({
    "Classe": class_names,
    "Acertos": acertos,
    "% Acertos": np.round(perc_acertos,2),
    "Erros": erros,
    "% Erros": np.round(perc_erros,2)
})

print(resultado)
print()


#Gráfico
plt.figure(figsize=(10,6))

x = np.arange(len(class_names))

largura = 0.35

plt.bar(
    x - largura/2,
    acertos,
    largura,
    label='Acertos'
)

plt.bar(
    x + largura/2,
    erros,
    largura,
    label='Erros'
)

# valores acima das barras
for i in range(len(class_names)):

    plt.text(
        x[i] - largura/2,
        acertos[i] + 1,
        f'{acertos[i]}\n({perc_acertos[i]:.1f}%)',
        ha='center',
        fontsize=9
    )

    plt.text(
        x[i] + largura/2,
        erros[i] + 1,
        f'{erros[i]}\n({perc_erros[i]:.1f}%)',
        ha='center',
        fontsize=9
    )

plt.xticks(
    x,
    class_names
)

plt.ylabel("Quantidade de Imagens")

plt.xlabel("Classes")

plt.title(
    "Acertos e Erros por Classe no Conjunto de Teste"
)

plt.legend()

plt.tight_layout()

plt.show()

"""Item h) (0,1) Implemente a tomada de tempo do processo de treinamento e
validação em minutos, que deve ser exibido na tela e ser colocado no
arquivo .pdf como parte do resultado.
"""

tempo_minutos = (fim - inicio) / 60

print(
    f"Tempo total de treinamento e validação: "
    f"{tempo_minutos:.2f} minutos"
)